const { connector } = require('./databaseUtil');

const empPersonalSchema = {
   title: { type: String, required: true },
   empFirstName: { type: String, required: true },
   empMiddleName: { type: String, required: true },
   empLastName: { type: String, required: true },
   bloodGroup: { type: String, required: true },
   dob: { type: Date, required: true },
   birthPlace: { type: String, required: true },
   motherTongue: { type: String, required: true },
   gender: { type: String, required: true },
   religion: { type: String, required: true },
   numOfChildren: { type: Number, required: true },
   originalCastCategory: { type: String, required: true },
   caste: { type: String, required: true },
   subCaste: { type: String, required: true },
   spouseMailAddress: { type: String, required: true },
   spouseMobileNo: { type: Number, required: true },
   emrgContactNo: { type: Number, required: true },
   emrgContactPersonName: { type: String, required: true },
   empMobileNo: { type: Number, required: true },
   panNumber: { type: String, required: true },
   aadharCardNo: { type: Number, required: true },
   creditCardNumber: { type: Number, required: true },
   drivingLicenceNo: { type: String, required: true },
   drivingLicenceExpiry: { type: Date, required: true },
   passportNumber: { type: String, required: true },
   licId: { type: String, required: true },
   identificationMark: { type: String, required: true },
   addressTypePermanant: { type: String, required: true },
   permanantPlotNo: { type: String, required: true },
   permanantStreet: { type: String, required: true },
   permanantAddress: { type: String, required: true },
   permanantAddress2: { type: String, required: true },
   permanantCity: { type: String, required: true },
   permanantTahshil: { type: String, required: true },
   permanantDistrict: { type: String, required: true },
   permanantState: { type: String, required: true },
   permanantCountry: { type: String, required: true },
   permanantPincode: { type: Number, required: true },
   addressTypeCorrespondance: { type: String, required: true },
   correspondancePlotNo: { type: String, required: true },
   correspondanceStreet: { type: String, required: true },
   correspondanceAddress: { type: String, required: true },
   correspondanceAddress2: { type: String, required: true },
   correspondanceCity: { type: String, required: true },
   correspondanceTahshil: { type: String, required: true },
   correspondanceDistrict: { type: String, required: true },
   correspondanceState: { type: String, required: true },
   correspondanceCountry: { type: String, required: true },
   correspondancePincode: { type: Number, required: true },
   maritalStatus: { type: String, required: true },
   maidenFirstName: { type: String, required: true },
   maidenMiddleName: { type: String, required: true },
   maidenLastName: { type: String, required: true },
   isNameChangedBefrore: { type: Boolean, required: true },
   previousFirstName: { type: String, required: true },
   previousMiddleName: { type: String, required: true },
   previousLastName: { type: String, required: true },
};

const empPersonal = new connector.model('Employee_Personal', empPersonalSchema);

module.exports = {};
